spring.application.name=educonecta-poc
server.port=8080

# Conexao com o MongoDB local (MongoDB Community Edition, visivel no Compass)
educonecta.mongodb.uri=mongodb://localhost:27017
educonecta.mongodb.database=educonecta

# Swagger UI disponivel em http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
